version: '3.4'

services:
  eshopwebmvc:
    image: ${DOCKER_REGISTRY-}eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
  createimage:
    build: .
    image: shirnissan/eshoponweb:${BUILD_NUMBER}

